=== iudx/iudx-ld/base_schemas/iudx_resourceItem_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "id": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_resourceItem_schema.json",
    "title": "IUDX-LD ResourceItem",
    "description": "IUDX-LD ResourceItem",
    "type": "object",
    "properties": {
        "@context": {
            "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_common.json#/definitions/LdContext"
        },
        "id": {
            "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_common.json#/definitions/id"
        },
        "resourceServer": {
            "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_meta.json#/definitions/Relationship",
            "describes": "The resource server which hosts this resource item"
        },
        "itemDescription": {
            "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_meta.json#/definitions/Property",
            "describes": "Text description of this item."
        },
        "refDataModel": {
            "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_meta.json#/definitions/Relationship",
            "describes": "Reference to the data model for this resource item."
        },
        "provider": {
            "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_meta.json#/definitions/Relationship",
            "describes": "Link to the provider of this resource"
        },
        "location": {
            "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_meta.json#/definitions/GeoProperty"
        },
        "itemStatus": {
            "$ref": "https://raw.githubusercontent.com/rbccps-iisc/iudx-schemas/master/base_schemas/v0.0.1/iudx_meta.json#/definitions/Property"
        },
        "createdAt" : {
            "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_common.json#/definitions/createdAt"
        },
        "modifiedAt" : {
            "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_common.json#/definitions/modifiedAt"
        },
        "deprecatedAt" : {
            "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_common.json#/definitions/deprecatedAt"
        },
        "additionalProperties": {
            "anyOf": [
                {
                    "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_meta.json#/definitions/Property"
                },
                {
                    "$ref": "https://raw.githubusercontent.com/rraks/iudx-ld/master/base_schemas/iudx_meta.json#/definitions/Relationship"
                }
            ]
        }
    }
}

=== iudx/iudx-ld/ex_items/testItem.json
{
    "@context": [
        "http://schema.org/test"
    ],
    "id": "test:testResource",
    "itemDescription": "Test Resource Description",
    "refDataModel": "http://example.com/testDatamodel.json",
    "provider": {
        "type": "Relationship",
        "object": "test:relation:ship"
    },
    "location": {
        "type": "GeoProperty",
        "value": {
            "type": "Point",
            "coordinates": [13,17]
        }
    },
    "itemStatus": "active",
    "createdAt": "2018-11-13T20:20:39+00:00"
}
