=== iudx/iudx-ld/base_schemas/v0.0.0/resourceServerGroup_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "id": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/iudx_resourceServer_schema.json",
    "title": "IUDX-LD ResourceServerGroup",
    "description": "Describes a set of resources (referred to as resourceSeverGroup) within a  ResourceServer. It is assumed that the resources withing a resourceSever Group share same dataModel, API objects, resource Server and provider.",
    "type": "object",
    "properties": {
        "@context": {
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/LdContext"
        },
        "id": {
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/id"
        },
        "name": {
           "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/miscSchemaOrgDefs.json#/definitions/name",
           "describes": "Name for the resource server group."
        },
        "tags": {
            "describes": "Array of keywords describing this resourceSeverGroup.",
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/tags"
        },
        "refBaseSchema": {
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/refBaseSchema",
            "describes": "Base schema for this item"
        },
        "provider": {
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/provider",
            "describes": "Link to the provider of this resource group. It is assumed that group of resources belonging to a given resource group share the same 'provider' who can provide authorisation to the 'group APIs' related to this group of resources. "
        },
        "resourceServer": {
            "describes": "Link to the ResourceServer catalog entity to which this group of resources belong",
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/resourceServer"
        },
        "refDataModel": {
            "describes": "Reference to the data model for this resource item.",
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/refDataModel"
        },
        "authorizationServerInfo": {
            "describes": "Information associated with obtaining authorization for accessing data from this resource item. It includes URI for the authorization server and authorization Type applicable for this item.",
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/authorizationServerInfo"
        },
        "resourceType": {
            "describes": "Type of the resource",
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/resourceType"
        },
        "itemDescription": {
            "describes": "Text description of this resource group.",
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/itemDescription"
        },
        "itemType": {
            "describes": "iudx item type",
            "allOf": [{
               "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/itemType"
            }],
            "properties": { 
               "value": {
                  "enum": ["resourceServerGroup"]
               }
            }
        },
        "accessInformation": {
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/accessInformation"
        },
        "itemStatus": {
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/itemStatus"
        },
        "dataAttributeList":{
           "describes": "Subset of data model attributes that are available in the resource server data.",
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/dataAttributeList"
        },
        "createdAt" : {
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/createdAt"
        },
        "modifiedAt" : {
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/modifiedAt"
        },
        "deprecatedAt" : {
            "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_defs.json#/definitions/deprecatedAt"
        }
    },
    "additionalProperties": {
        "anyOf": [
            {
                "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/core_defs.json#/definitions/Property"
            },
            {
                "$ref": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/core_defs.json#/definitions/Relationship"
            }
        ]
    },
    "required": ["id", "name", "tags", "refBaseSchema", "resourceServer", "itemDescription", "refDataModel", "provider", "itemType"]
}

=== iudx/iudx-ld/base_schemas/v0.0.0/examples/exResourceServerGroup.json
{
    "@context": [
        "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/core_context.json",
        "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_context.json",
        "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/miscSchemaOrgDefs.json",
        "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/geometry-schema.json"
    ],
    "id": "7493458asdgdbe099540",
    "name": "aqm-bosch-climo",
    "tags": { "type": "Property",
        "value": [ "environment", "air-quality", "climate", "air", "pollution", "SO2", "CO2", "CO", "NO", "NO2", "PM2.5", "PM10", "Humidity", "Temperature", "Ozone", "O", "Noise", "Light", "UV" ]
    },
    "accessInformation": [
      {
        "accessObjectType": "OpenAPI",
        "accessObjectURL": "https://abc.climo.org/APIs",
        "accessObject": {
            "object": "https://raw.githubusercontent.com/iudx/iudx-ld/master/data_models/environment/airQuality/examples/exApiObject_env_aqm_climoPune_0.json",
            "type": "Relationship"
        }
      }
    ],
    "createdAt": {
        "type": "TimeProperty",
        "value": "2019-06-20T15:30:06.093121"
    },
    "itemDescription": "Describes the resource group for bosch climo air quality monitor devices in Pune IBM-IOC resource server.",
    "itemStatus": {
        "type": "Property",
        "value": "active"
    },
    "itemType": {
        "type": "Property",
        "value": "resourceServerGroup"
    },
    "authorizationServerInfo": {
        "type": "Property",
        "value": {
            "authServer": "http://auth.example.org",
            "authType": "iudx-auth"
        }
    },
    "provider": {
        "object": "urn:iudx-cat:ae48f2-5c01e8-3feda9",
        "type": "Relationship"
    },
    "refBaseSchema": {
        "object": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/resourceServerGroup_schema.json",
        "type": "Relationship"
    },
    "refDataModel": {
        "object": "https://raw.githubusercontent.com/iudx/iudx-ld/master/data_models/environment/airQuality/env_aqm_climoPune_0.json",
        "type": "Relationship"
    },
    "resourceServer": {
        "object": "urn:iudx-cat:636485-9454054-29459495",
        "type": "Relationship"
    }
}

=== iudx/iudx-ld/base_schemas/v0.0.0/examples/resServerGrp_Pune_bosch_climo_aqm.json
{
    "@context": [
        "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/core_context.json",
        "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/common_context.json",
        "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/miscSchemaOrgDefs.json",
        "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/geometry-schema.json"
    ],
    "id": "7493458asdgdbe099540",
    "name": "aqm-bosch-climo",
    "tags": { 
        "type": "Property",
        "value": [ "environment", "air quality", "climate", "air", "aqi", "aqm", "climo", "pollution", "so2", "co2", "co", "no", "no2", "pm2.5", "pm10", "humidity", "temperature", "ozone", "o3", "noise", "light", "uv" ]
    },
    "accessInformation" : {
      "type" : "Property",
      "value" : [ {
        "accessObjectURL" : "https://bosch.climo.org/APIs",
        "accessObject" : {
          "type" : "Relationship",
          "value" : "https://raw.githubusercontent.com/iudx/iudx-ld/master/data_models/environment/airQuality/examples/exApiObject_env_aqm_climoPune_0.json"
        },
        "accessObjectType" : "OpenAPI"
      } ]
    },
    "createdAt": {
        "type": "TimeProperty",
        "value": "2019-06-20T15:30:06.093121"
    },
    "itemDescription": "Describes the resource group for bosch climo air quality monitor devices in Pune IBM-IOC resource server.",
    "itemStatus": {
        "type": "Property",
        "value": "active"
    },
    "itemType": {
        "type": "Property",
        "value": "resourceServerGroup"
    },
    "provider": {
        "value": "urn:iudx-cat:ae48f2-5c01e8-3feda9",
        "type": "Relationship"
    },
    "refBaseSchema": {
        "value": "https://raw.githubusercontent.com/iudx/iudx-ld/master/base_schemas/v0.0.0/resourceServerGroup_schema.json",
        "type": "Relationship"
    },
    "refDataModel": {
        "value": "https://raw.githubusercontent.com/iudx/iudx-ld/master/data_models/environment/airQuality/env_aqm_climoPune_0.json",
        "type": "Relationship"
    },
    "resourceServer": {
        "value": "urn:iudx-cat:636485-9454054-29459495",
        "type": "Relationship"
    }
}
